baseURL = "https://sreeramp.runs-on.dev/"
locale = "en-us"
title = "Sreeram P"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.158.0"

  [[module.imports]]
    path = "github.com/tom2almighty/hugo-narrow"
